name: Validate PR

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4

      - name: Validate CHANGELOG and PR body
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail

          # Check that CHANGELOG.md is modified in this PR
          echo "Checking for CHANGELOG.md updates..."
          files_changed=$(git diff --name-only origin/${{ github.base_ref }}.HEAD || true)
          echo "Files changed:\n$files_changed"

          if ! echo "$files_changed" | grep -qE "(^|/)CHANGELOG.md$"; then
            echo "ERROR: Please add an entry to CHANGELOG.md describing your change."
            exit 1
          fi

          # Ensure PR body includes the required checklist items from CONTRIBUTING.md
          echo "Checking PR body for required checklist..."
          pr_body="${{ github.event.pull_request.body || '' }}"

          required_items=(
            "Tests added/updated"
            "Linter/formatter run"
            "Documentation updated"
            "CHANGELOG.md updated"
          )

          missing=()
          for item in "${required_items[@]}"; do
            if ! echo "$pr_body" | grep -qiF "$item"; then
              missing+=("$item")
            fi
          done

          if [ ${#missing[@]} -ne 0 ]; then
            echo "ERROR: PR body is missing the following checklist items:" >&2
            for m in "${missing[@]}"; do
              echo " - $m" >&2
            done
            echo "Please update the PR description to include the checklist (see CONTRIBUTING.md)." >&2
            exit 1
          fi

          echo "Validation passed."
